// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SweatFlexEF.Models;

public partial class Exercise
{
    public int Id { get; set; }

    public string Creator { get; set; } = null!;

    public string Name { get; set; } = null!;

    public int Type { get; set; }

    public int Musclegroup { get; set; }

    public int? Equipment { get; set; }

    public string? Description { get; set; }

    public virtual User CreatorNavigation { get; set; } = null!;

    public virtual Equipment? EquipmentNavigation { get; set; }

    public virtual Musclegroup MusclegroupNavigation { get; set; } = null!;

    public virtual ICollection<TrainingExercise> TrainingExercises { get; set; } = new List<TrainingExercise>();

    public virtual Type TypeNavigation { get; set; } = null!;

    public virtual ICollection<WorkoutExercise> WorkoutExercises { get; set; } = new List<WorkoutExercise>();
}