// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace SweatFlexEF.Models
{
    public partial class fn_ValidatLoginResult
    {
        public string Id { get; set; } = default!;
        public int Role { get; set; }
        public string FirstName { get; set; } = default!;
        public string LastName { get; set; } = default!;
        public string Email { get; set; } = default!;
        public string? CoachId { get; set; }
    }
}
