// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SweatFlexEF.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SweatFlexEF.Models
{
    public partial interface ISweatFlexContextProcedures
    {
        Task<int> CreateUserAsync(string UserIdInput, int? RoleInput, string FirstNameInput, string LastNameInput, string EmailInput, string PasswordInput, string CoachIdInput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
