// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using SweatFlexEF.Models;

namespace SweatFlexEF.Models
{
    public partial class SweatFlexContext
    {

        [DbFunction("fn_getNextSessionId", "dbo")]
        public IQueryable<fn_getNextSessionIdResult> fn_getNextSessionId(string UserIdInput)
        {
            return FromExpression(() => fn_getNextSessionId(UserIdInput));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_getNextSessionIdResult>().HasNoKey();
        }
    }
}
