// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using SweatFlexEF.Models;

namespace SweatFlexEF.Models
{
    public partial class SweatFlexContext
    {

        [DbFunction("fn_ValidatLogin", "dbo")]
        public IQueryable<fn_ValidatLoginResult> fn_ValidatLogin(string EmailInput, string PasswordInput)
        {
            return FromExpression(() => fn_ValidatLogin(EmailInput, PasswordInput));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_ValidatLoginResult>().HasNoKey();
        }
    }
}
