// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SweatFlexEF.Models;

public partial class User
{
    public string Id { get; set; } = null!;

    public int Role { get; set; }

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string? CoachId { get; set; }

    public bool? IsActive { get; set; }

    public Guid PasswordId { get; set; }

    public virtual User? Coach { get; set; }

    public virtual ICollection<Exercise> Exercises { get; set; } = new List<Exercise>();

    public virtual ICollection<User> InverseCoach { get; set; } = new List<User>();

    public virtual PasswordDepot Password { get; set; } = null!;

    public virtual UserRole RoleNavigation { get; set; } = null!;

    public virtual ICollection<TrainingExercise> TrainingExercises { get; set; } = new List<TrainingExercise>();

    public virtual ICollection<Workout> Workouts { get; set; } = new List<Workout>();
}