// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SweatFlexEF.Models;

public partial class WorkoutExercise
{
    public int Id { get; set; }

    public int ExerciseId { get; set; }

    public int WorkoutId { get; set; }

    public int Index { get; set; }

    public virtual Exercise Exercise { get; set; } = null!;

    public virtual Workout Workout { get; set; } = null!;
}